default: &default
  pool: 5
  timeout: 5000
  adapter: mysql2
  encoding: utf8
  host: localhost
  username: root
  password: root

development:
  <<: *default
  database: sm_1_dev

test:
  <<: *default
  database: sm_1_test

production:
  <<: *default
  database: sm_1_prd
